<a href="https://colab.research.google.com/github/fhdkmrn/BDSI_Python_Tutorial/blob/master/Python_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Tutorial


*References:*
1. https://docs.python.org/3/tutorial/
2. https://docs.python.org/3/library/
3. http://cs231n.github.io/python-numpy-tutorial/
4. https://github.com/donnemartin/data-science-ipython-notebooks

### Let's run our slides first!

```
jupyter notebook
```


In [0]:
print ('Hello Python3!')

# Python Basics

- Variables and Types
- Operators
- Containers
- Functions
- Control Flow


### Variables and Types

In [0]:
x = 3
print (x, type(x))

In [0]:
print (x + 3)   # Addition;
print (x - x)   # Subtraction;
print (x * 2)   # Multiplication;
print (x ** 3)  # Exponentiation;

In [0]:
print (x)
x += 1
print (x)
x = x + 1
print (x)  # Prints "4"
x *= 2
print (x)  # Prints "8"

In [0]:
y = 2.5
print (type(y)) # Prints "<class 'float'>"
print (y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

In [0]:
print (17 / 3)   # return float
print (17 // 3)  # return integer
print (17 % 3)   # Modulo operation

In [0]:
t, f = True, False # Note the Captilzation!
print (type(t)) # Prints "<class 'bool'>"

In [0]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (... t)   # Logical NOT;
print (t != f)  # Logical XOR;

In [0]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print (hello, len(hello)) #len gives you length of sequence

In [0]:
hw = hello + ... + world  # String concatenation
print (hw)  # prints "hello world"

In [0]:
#Adding strings and numbers
...

You can find a list of all string methods in the [document](https://docs.python.org/3/library/string.html).

### Containers

Python includes several built-in container types: lists and dictionaries

In [0]:
x = [1, 2, 3, 'a', 'b', 'c'] #Create a list
print (x[0])  # access by index
print (...)    # index can be negative

In [0]:
#What happens is our index is too big? 
...

In [0]:
x = [1, 2, 3, 'a', 'b', 'c'] + ... # list append with the + operator

In [0]:
x.append('element')
print (x)
print (x.pop(), x)
print(... in x)

In [0]:
x = [1, 2, 3, 4, 5]
print (x[2:])
print (x[:3])
print (x[2:5])
...  # modify elements in list
print (x)

In [0]:
new_dct = {}

new_dct['hello'] = 'world!'

print (new_dct)
print (new_dict['hello'])

In [0]:
# Let's change the value of some key
...

In [0]:
initialized_dct = {'hello': 'world!', 'it\'s!': 'me!', 'unexpected_list': ["woah", "a", "list!"]}
print (initialized_dct)

print (initialized_dct.keys())
print (initialized_dct.values())
print (initialized_dct.items())

In [0]:
#Issue with assignment operations

first_list = [1,2,3]
second_list = first_list

second_list[2] = 100

print (first_list)

In [0]:
#Fixing the assignment operation issue

first_list = [1,2,3]
...

second_list[2] = 100

print (first_list)

In [0]:
#Exercise 1

fib = ['hello', 'hi', 'hey', 'hola', 'heyo', 'sup', 'howdy']

...

...

...

### Functions

Python functions are defined using the def keyword. For example:

In [0]:
def hours_and_minutes(minutes): #Define function, provide arguments
    n_hours = minutes // 60
    n_minutes = minutes % 60 
    ... 

print (hours_and_minutes(181))
print (hours_and_minutes(72))

In [0]:
print (n_minutes)

In [0]:
#Exercise 2

def farenheight_to_celcius(f):
    ...

    return c

print (farenheight_to_celcius(98.6))

### Control Flow

Conditional statements and loops can purposefully control the order of code that is run

In [0]:
#An example of an if-elif-else clause

day = ...

... day == 'Tuesday':
    print('Taco Time!')
elif day == 'Saturday' ... day == 'Sunday':
    print('The Weekend!')
...:
    print('Just Another Day')

In [0]:
#Looping through a container

animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

In [0]:
animals = ['cat', 'dog', 'monkey']
for i in ...:
    print (animals[i])

In [0]:
lst = [1,2,3,4,5]
squared_lst = []
for x in lst:
    ...
print (squared_lst)

In [0]:
#List comprehension

squared_lst2 = [num**2 ... num ... lst]
print (squared_lst2)

In [0]:
lst = [1,2,3,4,5]
squared_even_lst = []
for num in lst:
    ...:
        squared_lst.append(...)
print (squared_even_lst)

In [0]:
#List comprehension with if

squared_even_lst2 = [num**2 ... num ... lst ...]

print (squared_even_lst)

In [0]:
#Print 'Not there yet! Until i gets to 10'
i = 0

while ...:
    print('Not there yet!')
    ...
print(i)

In [0]:
#Example function definition: mode of a list

ex_lst = [1,2,5,2,1,4,5,1,3,1,1,2,2,2,2,5,4,2]

def mode(lst):
    ...
    for num in ex_lst: 
        if ...:
            ...
        else:
            ...
    ...
    for ... in ...:
        if ...:
            ...
            ...
    ...
print (mode(ex_lst))

2


In [0]:
#Exercise 3

data = ['michigan', 1, 'stats', 3.33, 'hello']

...

print (words_list)
print (numbers_list)

In [0]:
#Exercise 4

dct = {'Janice': 3, 'Fred': 2, 'Gregg': 8, 'Gloria': 1}

...

print (only_odd(dct))

# Modules

- import modules
- numpy
- pandas
- matplotlib


In [0]:
import math

print (math.sqrt(16))

... math import sqrt
print (sqrt(16))

import math ... m

print (m.sqrt(16))

### NumPy

In [0]:
import numpy as np

In [0]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)

In [0]:
b = np.array([[0, 2, 4], [1, 3, 5]], dtype = np.float64)
print(b)
print(b.shape) # Two rows, Three columns

In [0]:
print (a + 1)

print (a * 2)

print (a + (2 * a))

In [0]:
print (...) # What values in a are greater than 1

print (...) # What values in a are equal to 1

In [0]:
b = np.array([[0, 2, 4], [1, 3, 5]], dtype = np.float64)

print (np.sum(b)) # Sum all elements in b

print (np.sum(b, axis = ...)) # Sum all elements in b along column axis

print (np.median(b)) # Median of all elements in b

print (np.median(b, axis = ...)) # Median of elements in b along row axis

In [0]:
np.arange(..., ..., ...) # Create array that starts at 5, ends at 10 (non-inclusive), at steps of 0.5

In [0]:
np.zeros(5)  # Create an array of all zeros

In [0]:
np.ones(shape=(3, 4), dtype = np.int32)  # Create an array of all ones

In [0]:
np.random.random((2,5))  # Create an array filled with random values

In [0]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

In [0]:
print (a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])

In [0]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
# but, we want to fix the issue of overwriting the original container 
b = ...
print (b)

print (a[0, 1])  
b[0, 0] = 77    # b[0, 0] is now different than the piece of data at a[0, 1]
print (a[0, 1])

In [0]:
# f is a view of contents of e
e = np.arange(12)
f = e....(3, 4)
print(f)

In [0]:
# We can get transpose of array by T attribute
print (f.T)

In [0]:
#Concatenate vectors 

a = np.array([1, 2, 3])
print(np....([a, a, a]))

In [0]:
b = np.array([[1, 2, 3], [4, 5, 6]])
d = b / 2.0
# Stack b and d vertically
print (...)

In [0]:
#Combine b and d horizontally
print (...)

In [0]:
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
print (v.dot(w))
print (np.dot(v, w))

In [0]:
# Sin, Cosine
print (np.sin(v))
print (np.cos(v))

### Matplotlib

- Plotting Lines
- Plotting Multiple Lines
- Scatter Plots
- Legend, Titles, etc.
- Subplots
- Histogram

In [0]:
import matplotlib.pyplot as plt

In [0]:
%matplotlib inline
# necessary for jupyter notebooks

In [0]:
plt.plot([1,2,3,4], 'o-')
plt.ylabel('some numbers')
plt.show()

In [0]:
#Two plots on the same line, with a legend and some labels

x = np.linspace(0,1,100)
y1 = x ** 2
y2 = np.sin(x)

plt.plot(..., 'r-', ...="parabola")
plt.plot(..., 'g--', ...="sine")
...
plt.xlabel(...)
plt.show()

In [0]:
# Create sample data, add some noise, plot a scatter plot 
x = np.random.uniform(1, 100, 1000)
y = np.log(x) + np.random.normal(0, .3, 1000)

...
plt.show()

#### Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [0]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# First plot
plt.subplot(2, 1, 1)
plt.plot(x, y_sin)
plt.title('Sine')

# Second plot
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

In [0]:
mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt....(x, 50, density=1, facecolor='g', alpha=0.75)

plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()